swagger: '2.0'

info:
  version: "0.0.0"
  title: E-Key

paths:
  /checks?fridToken={fridToken}&deiceMac={deiceMac}:
    post:
      description: |
        Checks the `Student` on lecture.
      parameters:
        - in: path
          name: fridToken
          description: Student identifier
          required: true
          type: number
          format: integer
        - in: path
          name: deiceMac
          description: Room identifier
          required: true
          type: string
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/Check'
        400:
          description: Wrong
  /teachers/find?surname={surname}:
    get:
      description: |
        Find all `Teacher`'s with **surname**.
      parameters:
        - in: path
          name: surname
          description: Teacher surname
          required: true
          type: string
      responses:
        200:
          description: Success
          schema:
            type: array
            items: 
              $ref: '#/definitions/Teacher'
  /lectures/now?group={group}:
    get:
      description: |
        Find the current `Lecture`.
      parameters:
        - in: path
          name: group
          description: Group name
          required: true
          type: string
      responses:
        200:
          description: Group have a lecture
          schema:
            $ref: '#/definitions/Lecture'
        204:
          description: Group doesn't have a lecture
        404:
          description: Group not found
  /lectures/dayly?day={day}&group={group}:
    get:
      description: |
        Returns `Lections` for **group** in **day**.
      parameters:
        - in: path
          name: day
          description: Day of week
          required: true
          type: integer
          format: int16
        - in: path
          name: group
          description: Group name
          required: true
          type: string
      responses:
        200:
          description: Group have lectures
          schema:
            type: array
            items:
              $ref: '#/definitions/Lecture'
        204:
          description: Group doesn't have lectures
        404:
          description: Group not found
  /students/{rfidToken}:
    get:
      description: |
        Returns `Student` data.
      parameters:
        - in: path
          name: rfidToken
          description: Student identyfier
          required: true
          type: integer
          format: int32
      responses:
        200:
          description: Valid token
          schema:
            $ref: '#/definitions/Student'
        404:
          description: Invalid token
  /students/{studentId}/checks:
    get:
      description: |
        Returns `Check`'s
      parameters:
        - in: path
          name: studentId
          description: Student id
          required: true
          type: string
      responses:
        200:
          description: Students checks
          schema:
            type: array
            items:
              $ref: '#/definitions/Check'
        404:
          description: Student not found
definitions:
  Student:
    type: object
    properties:
      studentId:
        type: string
      rfidToken:
        type: integer
        format: int32
      firstName:
        type: string
      lastName:
        type: string
  Check:
    type: object
    properties:
      checkId:
        type: integer
        format: int32
      checkTime:
        type: string
        format: date-time
      room:
        $ref: '#/definitions/Room'
      student:
        $ref: '#/definitions/Student'
  Group:
    type: object
    properties:
      groupId:
        type: integer
        format: int32
      groupName:
        type: string
      students:
        type: array
        items:
          $ref: '#/definitions/Student'
  Lecture:
    type: object
    properties:
      lectureId:
        type: integer
        format: int32
      lectureName:
        type: string
      lectureInterval:
        $ref: '#/definitions/LectureInterval'
      room:
        $ref: '#/definitions/Room'
      teacher:
        $ref: '#/definitions/Teacher'
      weekTwoness:
        type: integer
        #FIX THIS
        format: int32
      dayOfWeek:
        type: integer
        format: int32
      group:
        $ref: '#/definitions/Group'
  LectureInterval:
    type: object
    properties:
      lectureIntervalId:
        type: integer
        format: int32
      university:
        $ref: '#/definitions/University'
      startTime:
        type: string
        format: date-time
      lectureInterval:
        type: integer
        format: int64
  University:
    type: object
    properties:
      univerId:
        type: integer
        format: int32
      univerName:
        type: string
      lectures:
        type: array
        items:
          $ref: '#/definitions/Lecture'
      rooms:
        type: array
        items:
          $ref: '#/definitions/Room'
  Room:
    type: object
    properties: 
      roomId:
        type: integer
        format: int32
      deviceMac:
        type: integer
        format: int64
      university:
        $ref: '#/definitions/University'
  Teacher:
    type: object
    properties:
      teacherId:
        type: integer
        format: int32
      teacherName:
        type: string
      teacherSurname:
        type: string
      teacherPatronymic:
        type: string
